### ISSUE TITLE
Undefined values

### ISSUE THREAD

**Issue by logix2** [lukechadwick/linux-intel-undervolt-gui#2]
Using this application on my Ubuntu 18.10 desktop, I get "undefined mv" values when clicking the "Read Voltages" button. Here''s my CPU info:

```
$ sudo lshw -class processor
  *-cpu                     
       description: CPU
       product: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
       vendor: Intel Corp.
       physical id: 4
       bus info: cpu@0
       version: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
       serial: To Be Filled By O.E.M.
       slot: CPU 1
       size: 3269MHz
       capacity: 3900MHz
       width: 64 bits
       clock: 400MHz
       capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts flush_l1d cpufreq
       configuration: cores=4 enabledcores=4 threads=8
```

Let me know if there's any other information you need.

**Comment by sp-hy** [comment]
Hi there,

This is usually related to the app not finding the python script. Have you placed the undervolt.py file included in the zip in your distros home directory? Try that. If it's still not working you can install the script globally by issuing the following commands:

`sudo apt install python3-pip
`
`sudo -H pip3 install undervolt`

The app should then detect you've got it install globally and use that way instead.

**Comment by logix2** [comment]
It can find the python script. When it can't find it (if I remove it from my home folder), nothing changes when I click the "Read Voltages", but for me the values change from "0 mv" to "undefined".

**Comment by sp-hy** [comment]
Hmm, perhaps you CPU is unsupported.

Could you please go to the directory with the script in it and execute:

`sudo python undervolt.py -r`

or if you have installed globally

`sudo undervolt -r`

**Comment by logix2** [comment]
```
$ sudo python undervolt.py -r

temperature target: -0 (100C)
Traceback (most recent call last):
  File "undervolt.py", line 283, in <module>
    main()
  File "undervolt.py", line 278, in main
    voltage = read_offset(plane)
  File "undervolt.py", line 172, in read_offset
    write_msr(value_to_write)
  File "undervolt.py", line 47, in write_msr
    os.write(f, pack('Q', val))
OSError: [Errno 5] Input/output error
```

**Comment by sp-hy** [comment]
The issue is your CPU then sorry, from a quick search it seems this kind of voltage control is only possible on Intel CPUs with an integrated voltage controller starting with intel 4th Gen CPUs (i5-4xxx etc), as yours is a second gen this won't work.

I'd look into undervolting through your BIOS settings if available, as they are likely to have more granular and permanent settings for undervolting and clock control.
