### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by krouma** [lukechadwick/linux-intel-undervolt-gui#5]
Hi, I tried this app but it is not working. The GUI says `-undefined mv`.
Laptop: Dell G5 15 5587
CPU: Intel Core i7-8750H
Chipset: Intel HM370
OS: Fedora 29 Workstation
Kernel: 4.20.6-200.fc29.x86_64

I also tried running `sudo undervolt -r` but it also crashed

> temperature target: -2 (98C)
> Traceback (most recent call last):
>   File "/usr/local/bin/undervolt", line 11, in <module>
>     load_entry_point('undervolt==0.2.9', 'console_scripts', 'undervolt')()
>   File "/usr/local/lib/python3.7/site-packages/undervolt.py", line 275, in main
>     voltage = read_offset(plane)
>   File "/usr/local/lib/python3.7/site-packages/undervolt.py", line 170, in read_offset
>     write_msr(value_to_write)
>   File "/usr/local/lib/python3.7/site-packages/undervolt.py", line 45, in write_msr
>     os.write(f, pack('Q', val))
> PermissionError: [Errno 1] Operation not permitted

Thanks for your time

**Comment by sp-hy** [comment]
As per this thread: https://github.com/georgewhewell/undervolt/issues/16
Seems to be a secure boot issue on some devices, try disabling secure boot in the bios.

**Comment by krouma** [comment]
Yes, it was the secure boot, now it works. Thank you very much.
